config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resources :posts do
    member do
      post "/create_comment" => 'posts#create_comment', as: 'create_comment_to'
      post "/like_post" => 'posts#like_post', as: 'like_to'
    end
    collection do
      delete '/:id/destroy_comment' => 'posts#destroy_comment', as: 'destroy_comment'
    end
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :create_comment, :destroy_comment]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def create_comment
    unless user_signed_in?
      respond_to do |format|
        format.js { render 'please_login.js.erb'}
      end
    end
    
    @c = @post.comments.create(body: params[:body])
  end
  
  def destroy_comment
     @c = @post.comments.find(params[:body])
     @cn = @post.comments.find(params[:id])
     @link.destroy
     respond_to do |format|
     format.js {render delete_ok.js.erb}
    end 
     @c = @post.comments.remove(body: params[:body])

  end 
   

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in?%>
    <%= link_to 'SIGN OUT', destroy_user_session_path, method: :delete, data: {confirm: "꼭 삭제할꺼야?"}%>
  <% else%>
    <%= link_to 'SIGN IN', new_user_session_path%>
  <% end%>
  <%= link_to "HOME", root_path%>1
  <div class="container">
    <%= yield %>
  </div>


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/create_comment.js.erb
alert("댓글이 등록됨");

$('#body').val("");
$('#comment_table tbody').prefend( '<tr><td><%= @c.body %></td></tr>');

app/views/posts/delete_ok.js.erb
alert('삭제완료')

app/views/posts/destroy_comment.js.erb
alert("댓글이 삭제됨");

$('#body').val("");
$('#comment_table tbody').remove( '<tr><td><%= @c.body %></td></tr>');

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/please_login.js.erb
if(confirm("로그인이 필요합니다. \n 로그인 페이지로 이동할꺼니??"))
{
    location.href = "<%= new_user_session_path %>";
}

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= form_tag create_comment_to_post_path, id: "comment" do%>
<%= text_field_tag :body %>
<%= submit_tag "댓글달기"%>
<% end%>

<script>
$(function(){
  var form = $('#comment');
  form.on('submit', function(e){
    e.preventDefault();
    var contents = $('#body').val();
    console.log(contents)
    $.ajax({
      url: "<%= create_comment_to_post_path%>",
      method: "POST",
      data: {body: contents}
    });
  });
})

</script>
<table class= "table" id="comment_table">
  <thead>
    <tr>
    <th>댓글</th>
    </tr>
  </thead>
  <tbody>
    <% @post.comments.reverse.each do |p|%>
    <tr>
      <td><%= p.body %></td>
      <td><%= link_to "삭제",destroy_comment_posts_path ,id: "destroy_comment" %></td>
    </tr>
    <%end%>
  </tbody>
</table>
<script>
$(function(){
  var form = $('#destroy_comment');
  form.on('submit', function(e){
    e.preventDefault();
    var comment_id = $('this').attr('id');
    console.log(contents)
    $.ajax({
      url: '/comment_id/destroy_comment',
      method: "delete"
    });
  });
})
</script>

<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-warning" %> |
<%= link_to 'Back', posts_path ,class: "btn btn-success" %>
<%= link_to 'Like', like_to_post_path, class: "btn btn-info", id:"like_button" %>

<script>
$(function(){
$('#like_button').on('click', function(e){
  e.preventDefault();
  console.log("Like Button Clicked");
})
  form.on('submit', function(e){
    e.preventDefault();
    var contents = $('#body').val();
    console.log(contents)
    $.ajax({
      url: "<%= create_comment_to_post_path%>",
      method: "POST",
      data: {body: contents}
    });
  });
})